[workspace]
members = [ "runner", "library", "commons/rects", "solutions/2015/1", "solutions/2015/2", "solutions/2015/3", "solutions/2015/4", "solutions/2015/5", "solutions/2015/6", "solutions/2015/7", "solutions/2015/8", "solutions/2015/9",]
resolver = "2"
