[package]
name = "aoc_runtime"
version = "0.1.0"
edition = "2021"


[dependencies]
darling = "0.20.3"
linkme = "0.3.15"
proc-macro2 = "1.0.66"
quote = "1.0.33"
serde = { version = "1.0.185", features = ["derive"] }
thiserror = "1.0.47"
