[package]
name = "aoc_runtime"
version = "0.1.0"
edition = "2021"


[dependencies]
darling = "0.20.3"
either = "1.9.0"
proc-macro2 = "1.0.66"
quote = "1.0.33"
serde = { version = "1.0.185", features = ["derive"] }
syn = "2.0.29"
thiserror = "1.0.47"
