[package]
name = "aoc_2015_12"
version = "0.1.0"
edition = "2021"

[package.metadata.aoc.part1]
fun = "part1"

[package.metadata.aoc.part2]
fun = "part2"


[dependencies]
serde = "1.0.188"
serde_json = "1.0.107"
