[package]
name = "aoc_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc = { path = "../aoc" }
index = { path = "../solutions/index" }

chrono = "0.4.26"
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
thiserror = "1.0.47"
