[package]
name = "aoc_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc_runtime = { path = "../aoc_runtime" }
aoc_2015_1 = { path = "../solutions/2015/1" }

chrono = "0.4.26"
serde = { version = "1.0.185", features = ["derive"] }
serde_json = "1.0.105"
thiserror = "1.0.47"
