[package]
name = "aoc_2015_3"
version = "0.1.0"
edition = "2021"

[package.metadata.aoc.part1]
fun = "part1"
numeric = true

[package.metadata.aoc.part2]
fun = "part2"
numeric = true


[dependencies]
