[package]
name = "aoc_2015_4"
version = "0.1.0"
edition = "2021"

[package.metadata.aoc.part1]
fun = "part1"
long_running = true

[package.metadata.aoc.part2]
fun = "part2"
long_running = true


[dependencies]
md5 = "0.7.0"
