[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
aoc_library = { path = "../library" }
clap = { version = "4.3.22", features = ["derive"] }
lazy_static = "1.4.0"
