[package]
name = "aoc_2024_13"
version = "0.1.0"
edition = "2021"

[package.metadata.aoc.part1]
fun = "part1"

[package.metadata.aoc.part2]
fun = "part2"

[dependencies]
lazy-regex = "3.3.0"
nalgebra = "0.33.2"
